Add additional signatures and its implementation for history plugin
NubeIO/rubix-os pull request #119
Opened 2023-07-12 17:32 UTC by maharjanaman

Following signatures were added in `Marshaller` interface,
1. GetHosts
2. GetHistoryLogByHostUUID
3. CloneEdge
4. CreateBulkHistory
5. UpdateBulkHistoryLogs

2023-07-14 11:13 UTC, RaiBnod commented on module/shared/grpcmarshal.go
> +	_, err = g.DbHelper.Patch("bulk_history_logs", "", histLog)
Make another GRPC function `PatchWithoutParam` and use that one.

2023-07-14 11:14 UTC, RaiBnod requested changes
Include that requested change.

2023-07-15 14:04 UTC, maharjanaman commented on module/shared/grpcmarshal.go
> +	_, err = g.DbHelper.Patch("bulk_history_logs", "", histLog)
Updated with requested change. PTAL.

2023-07-16 03:46 UTC, RaiBnod approved these changes

2023-07-16 03:46 UTC, merged